import '@/styles/globals.sass'
import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Script src='/bulma.js'/>
      </body>
    </html>
  )
}
